### PR TITLE
Re-added uri parameters based on Mopidy config

### PR DESCRIPTION
**Pull request by svanrossem**
I've re-added  `traslate_uri` to give `uri` those parameters gstspotify need.

### CODE REVIEW

**Comment by kingosticks** [comment]
I'm intending to set these via the source-setup handler. This is the correct way to set generic source options. This is what I implemented in my latest version.

**Comment by kingosticks** [comment]
See https://github.com/mopidy/mopidy/pull/2060

**Comment by svanrossem** [comment]
> See [mopidy/mopidy#2060](https://github.com/mopidy/mopidy/pull/2060)

@kingosticks many thanks! Didn't see that PR on Mopidy itself.

**Comment by kingosticks** [comment]
Sorry, it wasn't obvious at all. But I think that's all we need in Mopidy itself for this to work so we are getting there.

**Pull request closed without merging**
